### ISSUE TITLE
Thank you for your work, which greatly improved my life experience.

### ISSUE THREAD

**Issue by everythingisjustfine** [IronKinoko/e-hentai-view#6]
Thank you very much for your contribution.  Leave this message to let you know that you saved a lot of people.  People like you make the world more peaceful.  Hope you can continue this project when you have time.  thanks again.

By the way, I ran into a problem where the thumbnails could not be loaded, just for your reference.
![28F7C515-345D-4868-8362-0A277BF8A8FF](https://user-images.githubusercontent.com/68576725/88009272-b00bcf00-cb44-11ea-945e-8ceece05f7c0.png)

In any case, this is already an amazing project.  Thank you for your contribution.

**Comment by IronKinoko** [comment]
This should be caused by not sign in to exhentai in the pwa application.  
**Just logging in to exhentai.appspot.com is not enough**

# Solution
## In PWA
You should re-install this PWA application, and follow the steps to sign in  again.

## In safari/chrome
You need to check if you can access the exhentai.org website, if you can access it normally, the thumbnails will be displayed normally

**Comment by everythingisjustfine** [comment]
https://t.me/anyfhakiebefj/116
不确定哪里做错了，所以录了个屏。会不会是ios14的原因🙈

**Comment by IronKinoko** [comment]
这个问题是因为safari有阻止跨站跟踪的功能, 所以ex的预览图片加载不出来

## 解决方案
设置 -> Safari浏览器 -> 在`隐私与安全性`中 关闭阻止跨网站跟踪

然后新打开应用就可以正常查看图片了

**Comment by everythingisjustfine** [comment]
解决了，非常感谢，已star，会持续关注！
